---
title: "Recitation For Week 01"
author: "Shun Zhu"
date: "Thursday, March 05, 2015"
output: pdf_document
---

***
### Food and Nutrient database in the US

### Description

A dataset containing 7058 food with different nutritoin 

### Format

A dataframe with 7058 rows and 16 variables

***


### Video 2 - Reading in the Dataset


```{r}

# Init working enviroment
setwd("F:/SkyDrive/Studying/MIT_COURSES/Th AnalyticsEdge_15.071x/lecture/week01")

# Get the current directory
getwd()

# Read the csv file
USDA = read.csv("F:/SkyDrive/Studying/MIT_COURSES/15-071-TheAnalyticsEdge/lecture/dataset/USDA.csv")

head(USDA)

# Structure of the dataset
str(USDA)

# Statistical summary
summary(USDA)

```



### Video 3 - Basic Data Analysis

```{r}

# Vector notation
USDA$Sodium

# Finding the index of the food with highest sodium levels
which.max(USDA$Sodium)

# Get names of variables in the dataset
names(USDA)

# Get the name of the food with highest sodium levels
USDA$Description[265]

# Create a subset of the foods with sodium content above 10,000mg
HighSodium = subset(USDA, Sodium>10000)

# Count the number of rows, or observations
nrow(HighSodium)

# Output names of the foods with high sodium content
HighSodium$Description

# Finding the index of CAVIAR in the dataset
match("CAVIAR", USDA$Description)

# Find amount of sodium in caviar
USDA$Sodium[4154]

# Doing it in one command!
USDA$Sodium[match("CAVIAR", USDA$Description)]

# Summary function over Sodium vector
summary(USDA$Sodium)

# Standard deviation
sd(USDA$Sodium)

sd(USDA$Sodium, na.rm = TRUE)
  
```

### Video 4 - Plots

```{r}

# Scatter Plots
plot(USDA$Protein, USDA$TotalFat)

# Add xlabel, ylabel and title
plot(USDA$Protein, USDA$TotalFat, xlab="Protein", ylab = "Fat", main = "Protein vs Fat", col = "red")

# Creating a histogram and maximum of VitaminC in the histogram is 2000
hist(USDA$VitaminC, xlab = "Vitamin C (mg)", main = "Histogram of Vitamin C")

# Add limits to x-axis
hist(USDA$VitaminC, xlab = "Vitamin C (mg)", main = "Histogram of Vitamin C", xlim = c(0,100))

# Specify breaks of histogram but break will work on 2000 
hist(USDA$VitaminC, xlab = "Vitamin C (mg)", main = "Histogram of Vitamin C", xlim = c(0,100), breaks = 100)

summary(USDA$VitaminC)

hist(USDA$VitaminC, xlab = "Vitamin C (mg)", main = "Histogram of Vitamin C", xlim = c(0,100), breaks=2000)

# Boxplots
boxplot(USDA$Sugar, ylab = "Sugar (g)", main = "Boxplot of Sugar")

```


### Video 5 - Adding a variable

```{r}

# Creating a variable that takes value 1 if the food has higher sodium than average, 0 otherwise
HighSodium = as.numeric(USDA$Sodium > mean(USDA$Sodium, na.rm=TRUE))
str(HighSodium)

# Adding the variable to the dataset
USDA$HighSodium = as.numeric(USDA$Sodium > mean(USDA$Sodium, na.rm=TRUE))
str(USDA)

# Similarly for HighProtein, HigCarbs, HighFat
USDA$HighCarbs = as.numeric(USDA$Carbohydrate > mean(USDA$Carbohydrate, na.rm=TRUE))
USDA$HighProtein = as.numeric(USDA$Protein > mean(USDA$Protein, na.rm=TRUE))
USDA$HighFat = as.numeric(USDA$TotalFat > mean(USDA$TotalFat, na.rm=TRUE))

```


### Video 6 - Summary Tables

```{r}
# How many foods have higher sodium level than average?
table(USDA$HighSodium)

# How many foods have both high sodium and high fat?
table(USDA$HighSodium, USDA$HighFat)

# Average amount of iron sorted by high and low protein?
tapply(USDA$Iron, USDA$HighProtein, mean, na.rm=TRUE)

# Maximum level of Vitamin C in hfoods with high and low carbs?
tapply(USDA$VitaminC, USDA$HighCarbs, max, na.rm=TRUE)

# Using summary function with tapply
tapply(USDA$VitaminC, USDA$HighCarbs, summary, na.rm=TRUE)

```



